"""Added is_staff to User. Add default False value.

Revision ID: 00252021f336
Revises: 1d78fcf5e56e
Create Date: 2024-02-18 16:07:02.259571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00252021f336'
down_revision: Union[str, None] = '1d78fcf5e56e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
