"""Added is_superuser to User. Add default False value.

Revision ID: 5cab94c9e637
Revises: d54c5d1ba5d4
Create Date: 2024-02-18 16:20:31.131889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cab94c9e637'
down_revision: Union[str, None] = 'd54c5d1ba5d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
